
version: 2

models:
  - name: dbt_pokemon_movies_clean_pokemon_id
    description: "Liste des films pokemon lié à un pokemon" 
    columns:
      - name: imdbID
        description: "La clé primaire de la table"
        data_tests:
          - unique
          - not_null
      - name: Title
        description: "Le titre du film pokemon"
      - name: Released
        description: "La date de sortie"
      - name: Type
        description: "Le type ou genre du film"
      - name: Country
        description: "Le pays de sortie"
      - name: Ratings
        description: "La note du film"
        tests:
          - is_positif
      - name: TotalSeasons
        description: "Le nombre de saison"
      - name: pokemon_id
        description: "l'id du pokemon lié au film"
        tests:
          - not_null


  - name: dbt_pokemon_movies_silver
    description: "Liste des films pokemon nettoyé"
    columns:
      - name: imdbID
        description: "La clé primaire de la table"
        data_tests:
          - unique
          - not_null
      - name: Title
        description: "Le titre du film pokemon"
      - name: Released
        description: "La date de sortie"
      - name: Type
        description: "Le type ou genre du film"
      - name: Country
        description: "Le pays de sortie"
      - name: Ratings
        description: "La note du film"
      - name: TotalSeasons
        description: "Le nombre de saison"
      - name: pokemon_id
        description: "l'id du pokemon lié au film"



  - name: pokemon_list_silver
    columns: 
      - name: id
        tests: 
          - not_null
      - name: abilities
        description: "La liste des capacités du pokemon"
      - name: base_experience
        description: "L'experience de base"
      - name: cries
        description: "La liste des cries"
      - name: forms
        description: "La liste des formes"
      - name: game_indices
        description: "Les indices"
      - name: height
        description: "La taille"
      - name: items
        description: "Les éléments en sa possession"
      - name: is_default
        description: "Le pokemon par défaut"
      - name: location_area_encounters
        description: "Les emplacements"
      - name: name
        description: "Le nom"
      - name: order
        description: "La position dans la liste"
      - name: spicies
        description: "La liste de'espece"
      - name: stats
        description: "Les stats"
      - name: types
        description: "Le types"
      - name: weight
        description: "Le poids"


